[package]
name = "easy-log-forwarding"
version = "0.1.0"
edition = "2024"

[dependencies]
better-logger = { version = "2.1.1", features = ["relay", "native"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
chrono = "0.4.42"
tokio = { version = "1.48.0", features = ["full"] }